python_components/classifier/classifier.py

- Moves request.get within the try / except block. Prevents [issues](https://requests.readthedocs.io/en/latest/_modules/requests/exceptions/) with connecting with a single URL from failing the rest of the requests.
- Adds a timeout to requests to prevent hanging over two minutes on a single request
- Model prediction fails if the data it's working on doesn't have all of the columns the model expects. Fixed a bug when the data has more columns than the model expects, but still doesn't have all of the models the data needs, and we weren't adding the missing columns in correctly.

Small fixes to the document classifier script

---

python_components/crawler/Dockerfile
python_components/crawler/crawler.py
python_components/crawler/requirements.txt

* Initial commit of website crawler, which previously lived in a Hex notebook
* Addresses issue with missing file names for URLs with backslashes [ASAP-40](https://codeforamerica.atlassian.net/browse/ASAP-40) on L162-165 of `crawler.py`
* Now scrapes information from Cold Fusion Markup files [ASAP-70](https://codeforamerica.atlassian.net/browse/ASAP-70) on L137 & L106 of `crawler.py`
* TODO: Current behavior is to pass the script a URL, the depth of the crawl or a flag to use the sitemap, and a file path for an output. I'd like to integrate defaults for each site into the `config.json` file.
* TODO: There are three bare excepts that should be addressed eventually.
[ASAP-40]: https://codeforamerica.atlassian.net/browse/ASAP-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …

Initial commit of web crawling script

---

Gemfile
Gemfile.lock
app/controllers/configurations_controller.rb
app/models/document.rb
app/views/configurations/edit.html.erb
python_components/README.md
python_components/recommendation/Dockerfile
python_components/recommendation/lambda_function.py
python_components/recommendation/models.json
python_components/summary/Dockerfile
python_components/summary/config.json.example
python_components/summary/lambda_function.py

Some of our local lambda setup made assumptions that would not work in production. This PR makes adjustments to keep the best parity we can with the production environment, locally and to prevent copying API keys into our docker images.
We now store API keys in the localstack secret manager for development and testing environments. We no longer write the config.json file into the Docker image. Within the container the API keys are always pulled from secret manager.

1337 ready lambdas for aws

---

python_components/crawler/Dockerfile
python_components/crawler/crawler.py
python_components/crawler/requirements.txt

Addresses [ASAP-83](https://codeforamerica.atlassian.net/browse/ASAP-83?atlOrigin=eyJpIjoiOGRmZWNjY2Y4NzRhNGE5Yzg5MWViNzJlYzFiOTczYzIiLCJwIjoiaiJ9) by collecting the number of images and tables embedded within the PDF. 
In order to test this, please pull down this branch, build (`docker build -t asap_pdf:crawler .`) and run its docker container (`docker run --rm -it -v "$(pwd):/workspace" asap_pdf:crawler bash`), and then run the `crawler.py` script. I'd recommend either editing the crawl depth for a site within the `config.json` file (e.g., change SLC's to two and run on their site) or run over a smaller site (e.g., ours!) by adding this to the file:
```{json}
"https://codeforamerica.org/": {
"allow_list": ["https://codeforamerica.org/"],
"use_sitemap": false,
"depth": 2
}
```
Running …

Collect number of tables and number of images found in PDF

---

.github/workflows/ci.yml
.github/workflows/python_components.yml
Dockerfile
app/controllers/documents_controller.rb
app/javascript/controllers/filter_controller.js
app/javascript/controllers/hello_controller.js
app/javascript/controllers/index.js
app/models/document.rb
app/views/documents/index.html.erb
db/migrate/20250411193643_add_cascade_to_document_inference_fk.rb
lib/tasks/documents.rake
spec/features/document_spec.rb
spec/models/document_spec.rb

This PR includes a mix of quick wins for Sprint 4.
* Default sort to document category confidence, descending ([ASAP-103](https://codeforamerica.atlassian.net/jira/software/c/projects/ASAP/boards/54/backlog?selectedIssue=ASAP-103))
* Default filter bar to open ([ASAP-104](https://codeforamerica.atlassian.net/browse/ASAP-104?atlOrigin=eyJpIjoiYWRkYThiMDc0NDVjNDlhNTk3ZmE1N2IxM2JiNTgyOGMiLCJwIjoiaiJ9))
* Filenames in the document table should open the modal ([ASAP-101](https://codeforamerica.atlassian.net/browse/ASAP-101?atlOrigin=eyJpIjoiM2VlODc1Y2U3ZjI2NDQwMzg3MDYzM2RjNWJkNGQ5NzIiLCJwIjoiaiJ9))
* Convert insecure document urls to https
* Change default decision type ([ASAP-128](https://codeforamerica.atlassian.net/browse/ASAP-129?atlOrigin=eyJpIjoiZDlhYTAwMTNkNjg5NDQ3M2I1YmUyMzEyM2MyYjQ1MTk …

1337 sprint 4 quick wins

---

app/controllers/documents_controller.rb
app/javascript/controllers/dropdown_edit_controller.js
app/javascript/controllers/modal_controller.js
app/models/document.rb
app/models/site.rb
app/views/documents/_recommendation_list.html.erb
app/views/documents/index.html.erb
db/migrate/20250203181826_create_documents.rb
db/migrate/20250411210519_remove_category_default_value.rb
spec/features/document_spec.rb
spec/models/document_spec.rb
spec/requests/api/sites_spec.rb

* Removes "Other" document category, reconciles app document category list with python component. Makes document category a required field. [ASAP-123](https://codeforamerica.atlassian.net/browse/ASAP-123)
* Fix lingering active state of suggestions tab. [ASAP-134](https://codeforamerica.atlassian.net/browse/ASAP-134)
* Always show AI exception suggestion beneath human one. Add a magic wand icon. [ASAP-121](https://codeforamerica.atlassian.net/browse/ASAP-121)
[ASAP-123]: https://codeforamerica.atlassian.net/browse/ASAP-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ASAP-134]: https://codeforamerica.atlassian.net/browse/ASAP-134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ASAP-121]: …

1337 sprint 5 bugfixes

---

app/controllers/concerns/access.rb
app/controllers/configurations_controller.rb
app/controllers/documents_controller.rb
app/controllers/sites_controller.rb
app/models/site.rb
app/models/user.rb
app/views/layouts/application.html.erb
app/views/sites/index.html.erb
db/migrate/20250414172602_move_site_to_user.rb
db/migrate/20250414193153_add_admin_flag.rb
lib/tasks/documents.rake
lib/tasks/users.rake
spec/factories/sites.rb
spec/factories/users.rb
spec/features/admin_spec.rb
spec/features/document_spec.rb
spec/features/site_spec.rb
spec/models/site_spec.rb
spec/models/user_spec.rb

This PR adds support for multiple users to access a single site. It also adds an admin flag to the user model, which allows access to all sites. I decided to take the simpler approach of having users relate to sites, rather than creating a lookup table to relate them. We could always do that later, if we need it. Here is a break down of the specific changes:
* Removes user_id column and related ActiveRecord associations from sites.
* Adds site_id column and related ActiveRecord associations on user.
* Adds is_admin flag on user (to be set manually).
* Hides "Add Site" and "AI Settings" areas from non-admin users.
* Changes sites uniqueness settings to be universal rather than contextualized to users. Sites names and primary urls must now be unique.
* Adjusted and added test coverage.

Add support for multi-user sites

---

Gemfile
Gemfile.lock
app/controllers/documents_controller.rb
app/helpers/url_decoded_attribute_helper.rb
app/models/document.rb
app/models/site.rb
app/views/documents/_modal_content.html.erb
config/routes.rb
python_components/document_inference/document_inference/helpers.py
spec/features/document_spec.rb

We were originally using the rest-client library, [which is no longer maintained](https://github.com/rest-client/rest-client/issues/830). The client doesn't support 308 redirects that we are running into. We also still have problems with special characters in urls. This PR addresses these issues.
* Use HTTPParty instead of rest-client to serve files.
* Standardize url encoding and decoding functions.
* Allow for filenames that contain multiple dots.
* Update python components to also follow 308 redirects.

1337 fix document request regressions

---

app/controllers/documents_controller.rb
app/models/document.rb
app/models/site.rb
app/views/documents/index.html.erb
app/views/shared/_filter.html.erb
db/migrate/20250507231759_add_complexity.rb
lib/tasks/documents.rake
spec/features/document_spec.rb

Addresses [ASAP-136](https://codeforamerica.atlassian.net/browse/ASAP-136?atlOrigin=eyJpIjoiZDc4OTYwYzE2ODMzNDU4NWEzZDRkOTUyZDMzNTRhZjUiLCJwIjoiaiJ9). Adds simple / complex labels onto documents and allows the user to filter by them.
Two outstanding questions for feedback:
(1) Would adding this as a column to the main list view be helpful? We could add a hover over to explain how we constructed this score.
(2) What should the default behavior be called? I struggled with following other conventions (e.g., from "Document Type" -> "All Types", to "Complexity" -> "All Complexities" felt too wordy). 
[ASAP-136]: https://codeforamerica.atlassian.net/browse/ASAP-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Integrate pdf complexity into application

---

app/assets/stylesheets/application.tailwind.css
app/javascript/controllers/bulk_edit_controller.js
app/views/documents/_modal_content.html.erb
app/views/documents/index.html.erb
app/views/sites/insights.html.erb
spec/features/document_spec.rb

When we reworked the document table widths a few weeks ago, we created some scenarios where long document titles (which our stakeholders have) cause the table to explode from its container at a relatively large screen size. The app is not terribly mobile friendly. We probably don't intend it to be a mobile-first experience. However, it should be able to hold up a little bit better than it does. Let's do some very lightweight theming to try and improve the app on all screen sizes.
**Before screenshot:**
Filenames and keywords are forced to stay on one line, creating an inflexible layout.
**After screenshot**
Filenames and keywords are liquid wrapping to multiple lines.
**Smaller screens**
This PR adds:
* Better responsive theming for the documents and insights page.
* An animation and …

1337 light responsive theming

---

.github/pull_request_template.md
app/controllers/documents_controller.rb
app/helpers/url_decoded_attribute_helper.rb
app/models/document.rb
app/models/site.rb
app/views/documents/_modal_content.html.erb
spec/models/document_spec.rb

Our current url encoding strategy is as follows:
1. Encode documents before saving.
2. Decode documents when url getter is called.
Currently, we are fetch PDF content for via decoded urls. This works in most cases, but there are some documents with decoded urls that break the display process (identified by SLC). To make matters more complicated some documents were retrieved with escape sequences already present. We need to encode urls before requesting PDF content, but we need to make sure we don't double encode, which also breaks our display.
Our new url encoding strategy is as follows:
1. Import raw urls, but support previously imported encoded urls.
2. Decode recursively until they may no longer be decoded.
3. Encode and request.
This PR adds the following:
* Splits the url getter …

Asap 161 fix url edgecases

---

app/models/document.rb
app/views/layouts/centered.html.erb
python_components/document_inference/models.json
python_components/document_inference/requirements.txt

It seems like Google either severely rate limits experimental models or completely discontinued the one we were using. We need to switch to an equivalent, supported model.
This PR adds the following:
* Changes our document inference code to use  gemini-2.5-pro-preview-03-25 instead of gemini-2.0-pro-exp-02-05.
* Removes gemini-2.0-pro-exp-02-05 from model options
* **Unrelated:** Use the normalized_url to make AI requests. I notice some SLC urls that were not working correctly and this fixed it.
* **Unrelated:** Fix the title on the login page.

1337 model update 2025 05 15

---

app/models/document.rb
spec/features/document_spec.rb

Georgia’s feedback session highlighted that the search filter is not working all that well. Currently it uses a case insensitive like condition on just the filename. We’d like this to be a little more fuzzy. We think case insensitive like conditions on filename and url would be good. We also want to replace some characters, [ -_] with wildcards.
This PR changes the search method and adds a small test for search that fails on the dev branch.
**What additional steps are required to test this branch locally?**
None
**Are there any areas you would like extra review?**
Try out the search filter.
**Are there any rake tasks to run on production?**
No

Asap 174 improve search filter

---

app/models/document.rb
lib/tasks/documents.rake
spec/models/document_spec.rb

We went through several attempts to normalize and properly encode document urls. At one point in the past, we were using Ruby's `CGI.escape` method to sanitize URLs before storage. We then called `CGI.unescape` on retrieval before fetching the PDF. This worked in many cases, but broke some URLs that were already encoded in the csv site data. We moved away from the CGI based approach, but some URLs were still encoded with plus symbols.
CGI.escape documentation:
>URL-encode a string into application/x-www-form-urlencoded. Space characters (+" "+) are encoded with plus signs (+"+"+) url_encoded_string = CGI.escape("'Stop # => "%27Stop%21%27+said+Fred" 
This doesn't seem to cause problems for some stakeholder URLs. However, some SLC documents are broken. Here is an example:
Stored value:
``` …
```

Fix corrupted SLC urls

---

app/views/shared/_filter.html.erb
app/views/sites/insights.html.erb

We'd like to add some explanation of our document complexity data point.  We think a tooltip near the filter and on the insights page would make sense.
This PR adds said tooltips.
**Filter:**
<br/><br/>
<br/>
<br/>
<br/>
**Insights page:**
<br/>
<br/>
<br/>
<br/>
- **What additional steps are required to test this branch locally?**
None
- **Are there any areas you would like extra review?**
Welcome feedback on the copy.
- **Are there any rake tasks to run on production?**
No

Add tooltip to filters and insights page.

---

.github/workflows/eval.yml
app/models/document.rb
python_components/document_inference/models.json

[Google recommends](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions#legacy-stable) migrating Gemini 1.5 Pro models to Gemini 2.0 Flash. When I evaluated this branch (currently equivalent with main & dev), the summary performance under [Gemini 1.5 Pro (current LLM)](https://code-for-america.hex.tech/global/app/ASAP-Evaluation-Dashboard-0307kgWXk2slUqaovViuFf/latest?view=01984346-9dcb-7557-8f61-52a7ba322c2e) is very similar to [Gemini 2.0 Flash](https://code-for-america.hex.tech/global/app/ASAP-Evaluation-Dashboard-0307kgWXk2slUqaovViuFf/latest?view=01984346-f673-7aa2-aaca-ef144c3cdfae) (0.335 vs 0.333 using DeepEval's summarization score; 0.360 vs 0.386 ROUGE). These differences seem very slight to me, so this branch migrates our summarization functionality to …

Migrate Gemini 1.5-Pro models to Gemini 2.0 Flash models

---

app/mailers/application_mailer.rb
config/environments/production.rb
db/seeds.rb
terraform/main.tf
terraform/modules/cloudfront/data.tf
terraform/modules/cloudfront/local.tf
terraform/modules/cloudfront/main.tf
terraform/modules/cloudfront/outputs.tf
terraform/modules/cloudfront/templates/function.js.tftpl
terraform/modules/cloudfront/variables.tf
terraform/variables.tf

We want a production environment. It will have a new fancy domain, ada.codeforamerica.ai. We want this new domain to redirect to demo.codeforamerica.ai for now. We need a temporary redirect.
This PR adds the OpenTofu configuration for creating a CloudFront redirect. This code is mostly compliments of James A.
- **What additional steps are required to test this branch locally?**
Visit ada.codeforamerica.ai and make sure it redirects to demo.codeforamerica.ai.
- **Are there any areas you would like extra review?**
No
- **Are there any rake tasks to run on production?**
No

Add cloudfront module with temporary redirect for production domain.

---

app/controllers/documents_controller.rb
app/views/documents/_modal_content.html.erb
app/views/layouts/simple.html.erb
app/views/shared/iframe_error.html.erb
config/initializers/devise.rb

When a stakeholder unpublished or moves a document it's not clear what's going on in the app. Right now we just show a vague error message. We want something more robust.
We also think it would be good to explicitly show the document url and sources. Linking directly to the document causes an odd user interaction for urls that automatically force the download of the link. Showing the fields on the "PDF Details" tab seems like a good compromise.
This PR adds a nicely formatted message, when a document returns an error. It also adds the document urls and sources to the "PDF Details" tab.
- **What additional steps are required to test this branch locally?**
1. Create a site for Georgia Department of Revenue
2. Run the import command for your site. Something like: ` bin/rake …

Asap 214 better missing document strategies

---

.github/workflows/eval.yml
app/controllers/configurations_controller.rb
app/models/document.rb
app/views/configurations/edit.html.erb
config/environments/development.rb
config/environments/test.rb
python_components/document_inference/document_inference/helpers.py
python_components/document_inference/models.json
python_components/document_inference/requirements.txt
python_components/evaluation/evaluation/exception/evaluation.py
python_components/evaluation/evaluation/summary/evaluation.py
python_components/evaluation/evaluation/utility/asap_inference.py
python_components/evaluation/lambda_function.py
python_components/evaluation/models.json
python_components/evaluation/scripts/ci_invoke_evaluation_lambda.sh
terraform/modules/asap_pdf/main.tf
terraform/modules/lambda/main.tf
terraform/modules/lambda/variables.tf

The exception check is currently using gemini-2.5-pro-preview-03-25. We should investigate some other models and try to get off the preview.
This PR adds the following:
- Changes summary model from `gemini-flash-2.0` to `gemini-flash-2.5`.
- Changes exception model from `gemini-2.5-pro-preview-03-25` to `gemini-2.5-pro`
- Adds configuration and model support for OpenAI models
- Updates dependencies for document inference
- Improves the evaluation workflow
- More consistent error handling
- Waits for images to be deployed to Lambdas
- Ability to run a specific file
- Tracking inference duration
The following two dashboards were used in assessing evaluation results:
* Main dashboard: https://code-for-america.hex.tech/global/app/ASAP-Evaluation-Dashboard-0307kgWXk2slUqaovViuFf/latest
* …

Asap 221 migrate off preview model

---

app/models/site.rb
lib/tasks/documents.rake

SLC sent us a different list of departments and urls they'd like represented in the app.
This PR adjusts the rake script and department mapping.
- What additional steps are required to test this branch locally?
Reset the database:
`rails db:drop ; rails db:migrate ; rails db:setup`
Import just SLC's production docs: 
`bin/rake documents:import_documents["1", "db/seeds/site_documents/salt_lake_city.csv", true]`
Run the new rake script:
`bin/rake documents:update_department[1]`
- Are there any areas you would like extra review?
Just the above.
- Are there any rake tasks to run on production?
Yes, we'll need to reset the existing departments and run the new rake script.

Asap 223 slc dept bug

---

terraform/modules/deployment/main.tf

Every time we deploy or run the evaluation suite, we create new images that get pushed to our elastic container registry (ECR). As we pay for the storage, we don't want to keep every Lambda image indefinitely. We should add some auto deletion to our repositories.
This PR adds ECR lifecycle policies to our Lambda repositories. The Fargate (Rails app) repository already has a deletion policy. Our policy will remove images after 30 days regardless of tags.
- **What additional steps are required to test this branch locally?**
None
- **Are there any areas you would like extra review?**
No
- **Are there any rake tasks to run on production?**
No

Add lifecycle policy to all the registries.

---

app/mailers/application_mailer.rb
config/environments/development.rb
config/environments/production.rb
config/environments/staging.rb
config/environments/test.rb

We are trying to send emails from the production url on staging. That email address is not in our verified senders list. Let's change to the correct url.
This PR moves the default email addresses to environment configuration.

Add default site emails to config.

---

app/models/document.rb
app/models/site.rb
config/storage.yml
spec/models/document_spec.rb
spec/models/site_spec.rb

We have some vestigial S3 implementation on the document and site model.  Since we never stored the documents in S3, it's confusing to leave code for that storage around. Let's try to make it more clear what's going on.
This PR removes the document and site model's storage handling code and changes the storage config to use the tmp file system in all environments.

Remove unused S3-based storage for documents.

---

README.md
app/controllers/configurations_controller.rb
app/views/configurations/edit.html.erb
docs/README.md
docs/deployment.md
docs/python_components.md

We received some more feedback on documentation pain points.
This PR attempts to improve the documentation by
- Listing out current features
- Clarifying prerequisites and setup steps
- Consolidating all documentation besides the main README to the docs folder
It also makes the configuration settings for evaluations more obviously optional.

Asap 231 more documentation clarity
